### ISSUE TITLE
【咨询】KModbusRtuMaster中的values数据，为何是定义成IntArray而非ByteArray呢

### ISSUE THREAD

**Issue by hike2008** [crowforkotlin/KModbus#1]
<img width="770" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/43fab361-a640-4947-840a-cafddcb7ff0e">
如图

**Comment by crowforkotlin** [comment]
modbus寄存器和线圈都是十进制数据 这里实际上最后要把数据转成bytearray， 写成十进制可读性高，另外最新版本的这个还有点小问题 我已经在优化了 差不多了 大概几天后补传新的

**Comment by crowforkotlin** [comment]
![image](https://github.com/crowforkotlin/KModbus/assets/60876546/40ea86d3-4277-449c-816c-db8150a22d71)
ni你可以用Modbus Slave软件进行模拟数据

**Comment by crowforkotlin** [comment]
可以查看最新的main分lib_modbus模块， 补传文件，刚提交的

**Comment by hike2008** [comment]
好的，多谢

**Comment by hike2008** [comment]
再咨询个问题：
像这种定义为 一位小数的，在使用 KModbusRtuMaster.build 传输数据时，应该如何定义，这里是得自己重新封装一个 build 方法才行的吧？

<img width="563" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/8b09f268-8610-4fe6-b750-65264679bfe4">

**Comment by crowforkotlin** [comment]
对于浮点数 需要读写至少2位寄存器地址(短整型short范围)才能表示，ModbusRtuRespPacket.kt中通过toFlaot进行转换
1个寄存器16bit, 2个寄存器32bit float最少需要32bit才能满足
这和build没有关系，是读取写入思路要清晰

**Comment by crowforkotlin** [comment]
> 再咨询个问题： 像这种定义为 一位小数的，在使用 KModbusRtuMaster.build 传输数据时，应该如何定义，这里是得自己重新封装一个 build 方法才行的吧？
> 
> <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/8948629/295207026-8b09f268-8610-4fe6-b750-65264679bfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDU4NjIsIm5iZiI6MTcwNDgwNTU2MiwicGF0aCI6Ii84OTQ4NjI5LzI5NTIwNzAyNi04YjA5ZjI2OC04NjEwLTRmZTYtYjc1MC02NTI2NDY3OWJmZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTMwNjAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmMyOTMyODJhZmZkNDU3NDU5NTNlMDNhMTA1N2EzYTcxYmQ1YTZmY2Y4NGJiNGE5YTBhMjZmNTgwMTM4OWQzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SgdnWVUutJozrB9fKPbiGakaBpL_DVSmvpDYVK58ALg">

对于浮点数 需要读写至少2位寄存器地址才能表示一个float或者int32(一个寄存器数据类型为短整型short范围，除线圈)，ModbusRtuRespPacket.kt中通过toFlaot进行转换
1个寄存器16bit, 2个寄存器32bit float最少需要32bit才能满足
这和build没有关系，是读取写入思路要清晰

**Comment by crowforkotlin** [comment]
> 再咨询个问题： 像这种定义为 一位小数的，在使用 KModbusRtuMaster.build 传输数据时，应该如何定义，这里是得自己重新封装一个 build 方法才行的吧？
> 
> <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/8948629/295207026-8b09f268-8610-4fe6-b750-65264679bfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDY4ODksIm5iZiI6MTcwNDgwNjU4OSwicGF0aCI6Ii84OTQ4NjI5LzI5NTIwNzAyNi04YjA5ZjI2OC04NjEwLTRmZTYtYjc1MC02NTI2NDY3OWJmZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTMyMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2I5NmQ3ZGM2NjE3YWI3NjZlZDZkNWM3YzY5Y2QyZDcxNWM0MzExYmQ3ZjEyODkwOTUxYzA3Yjc5MzVkOWE1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QAkuGkHKc4MfotmaqfwQutXqTxIFYH1oDecSehdW0Eg">

几乎所有厂家对接modbus表示浮点数一般用多个寄存器表示 如果要写入浮点数也是写多个寄存器，写入int16即可

**Comment by crowforkotlin** [comment]
> 再咨询个问题： 像这种定义为 一位小数的，在使用 KModbusRtuMaster.build 传输数据时，应该如何定义，这里是得自己重新封装一个 build 方法才行的吧？
> 
> <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/8948629/295207026-8b09f268-8610-4fe6-b750-65264679bfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDcyNTMsIm5iZiI6MTcwNDgwNjk1MywicGF0aCI6Ii84OTQ4NjI5LzI5NTIwNzAyNi04YjA5ZjI2OC04NjEwLTRmZTYtYjc1MC02NTI2NDY3OWJmZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTMyOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFjMDFlMDFmZDE0YWNiOGIyOGM0NzVmMzZkMzcxMzA5MTM2NDM3OTRlMjk2YjQ2MzU0MWNhYjcxNzQ5NDVkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WQ5g4wf8I5jKDzHPRoZ72Zxp21if8R93137jf9q3EPg">

关于写入浮点数怎么实现？你可以通过Bytebuffer.wrap模拟一个浮点数16机制表示

> 再咨询个问题： 像这种定义为 一位小数的，在使用 KModbusRtuMaster.build 传输数据时，应该如何定义，这里是得自己重新封装一个 build 方法才行的吧？
> 
> <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/8948629/295207026-8b09f268-8610-4fe6-b750-65264679bfe4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDcyNTMsIm5iZiI6MTcwNDgwNjk1MywicGF0aCI6Ii84OTQ4NjI5LzI5NTIwNzAyNi04YjA5ZjI2OC04NjEwLTRmZTYtYjc1MC02NTI2NDY3OWJmZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMTMyOTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFjMDFlMDFmZDE0YWNiOGIyOGM0NzVmMzZkMzcxMzA5MTM2NDM3OTRlMjk2YjQ2MzU0MWNhYjcxNzQ5NDVkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WQ5g4wf8I5jKDzHPRoZ72Zxp21if8R93137jf9q3EPg">

你的需求很简单，只需要写入多个寄存器即可，看你的图片是十个寄存器，那么每2个寄存器一组，可以表示5个浮点数，至于保留多少位你可以自己吧读取的数据进行处理就好了
KModbusRtuRespPacket.kt 中toFloat可以设置读取的两个寄存器数据转成浮点数后保留几位

**Comment by hike2008** [comment]
非常感谢解答，
我之前对接过蓝牙的读写，在整体流程上挺类似，但是我当时写入时，是自己做的数据协议封装（蓝牙发送数据时，实体我是直接将字段转成协议定义的ByteArray进行发送的）；

modbus rtu是第一次接触，所以找到了你的封装，我的疑问其实是如何进行数据写入封装和解析（其实就是，数据实体转ByteArray我比较清晰，但是转成你封装的rtu的IntArray我就有点懵逼这个转换关系了）：

<img width="536" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/ea958e8a-b9bc-4df7-bb9e-3f0143774f6c">


<img width="844" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/2619b042-12ef-462a-85f5-a62868567318">

**Comment by hike2008** [comment]
以下是我蓝牙协议发送时的数据封装（是直接将对应数据实体转成了ByteArray）：

<img width="838" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/10fec152-cc6e-4c3f-b565-59153072d3fd">

**Comment by hike2008** [comment]
简单说，其实就是你这段的封装，不太理解，也就是modbus rtu协议不太理解为啥是下图的这种数据组装，这种IntArray和数据实体中的字段是如何对应关系和转换的：

<img width="1365" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/1444402e-5da7-41ce-9584-6e1339ab7696">

**Comment by crowforkotlin** [comment]
> 简单说，其实就是你这段的封装，不太理解，也就是modbus rtu协议不太理解为啥是下图的这种数据组装，这种IntArray和数据实体中的字段是如何对应关系和转换的：
> 
> <img alt="image" width="1365" src="https://private-user-images.githubusercontent.com/8948629/295383565-1444402e-5da7-41ce-9584-6e1339ab7696.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzg0MDcsIm5iZiI6MTcwNDg3ODEwNywicGF0aCI6Ii84OTQ4NjI5LzI5NTM4MzU2NS0xNDQ0NDAyZS01ZGE3LTQxY2UtOTU4NC02ZTEzMzlhYjc2OTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDkxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2U1MWRjZTJjZGQ3YTEzZjRhNTdlY2RhMmNkMzJkMzVmNzQzZDE0MjczOGUyYWNkOGEyMjRlNTFlY2QxZTk1MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.84zGTrJ5ObQnjMk2WoISQV3RoBgIgE4F1vvLO0M9QFA">

写多个线圈的时候 写入的数据是8bit一组，每一位都代表一个寄存器，当你写入8个寄存器的时候此时就是8bit刚好满足一个字节这里通过分8位为一组然后将8bit的array转成一个10进制，最后通过`output.writeInt8`写入十进制数据（ByteBufferOutputStream内部实现吧int8转成了bytearray写入）

**Comment by crowforkotlin** [comment]
> 以下是我蓝牙协议发送时的数据封装（是直接将对应数据实体转成了ByteArray）：
> 
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/8948629/295382795-10fec152-cc6e-4c3f-b565-59153072d3fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzg0MDcsIm5iZiI6MTcwNDg3ODEwNywicGF0aCI6Ii84OTQ4NjI5LzI5NTM4Mjc5NS0xMGZlYzE1Mi1jYzZlLTRjM2YtYjU2NS01OTE1MzA3MmQzZmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDkxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjllMmZkMDdjZTY2Zjg5NjI2ZmZjNmVmNzI1OGJmZmVhNWFhZjM1NjMxYWUzZTU2NWQ2MDdhOTMyMTQ3ZTcxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yP0RsCTqQ3b_P-luREOMPRoeAyyT7CdJLSO9LnD3aTE">

在modbus中，十进制更容易理解，因为寄存器存的数据都是int16（-32768 到 32767）（除了线圈只有01）,

**Comment by crowforkotlin** [comment]
> 非常感谢解答， 我之前对接过蓝牙的读写，在整体流程上挺类似，但是我当时写入时，是自己做的数据协议封装（蓝牙发送数据时，实体我是直接将字段转成协议定义的ByteArray进行发送的）；
> 
> modbus rtu是第一次接触，所以找到了你的封装，我的疑问其实是如何进行数据写入封装和解析（其实就是，数据实体转ByteArray我比较清晰，但是转成你封装的rtu的IntArray我就有点懵逼这个转换关系了）：
> 
> <img alt="image" width="536" src="https://private-user-images.githubusercontent.com/8948629/295381235-ea958e8a-b9bc-4df7-bb9e-3f0143774f6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzg0MDcsIm5iZiI6MTcwNDg3ODEwNywicGF0aCI6Ii84OTQ4NjI5LzI5NTM4MTIzNS1lYTk1OGU4YS1iOWJjLTRkZjctYmI5ZS0zZjAxNDM3NzRmNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDkxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmFhNzBiNzVlMDEzYTViOGQ5NGJiM2FmYzA4ZGViODc5YWI5NjQ5Yjc0NGQ5NzI5YTEwYzIyNDViNWYyOTY5ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0fhkUTO4NHLNwLyYXm9HXAM7qzO4y2T4moCxfeshqCw"> <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/8948629/295381144-2619b042-12ef-462a-85f5-a62868567318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4Nzg0MDcsIm5iZiI6MTcwNDg3ODEwNywicGF0aCI6Ii84OTQ4NjI5LzI5NTM4MTE0NC0yNjE5YjA0Mi0xMmVmLTQ2MmEtODVmNS1hNjI4Njg1NjczMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTBUMDkxNTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGE3NWVjM2NlMzgzNjBlMGYxNjBhOWRjZGE2YzdlZGU1Zjk4NzBlMzAzODA5YjQwZDcyMDA1ZmRiYzAyMWI3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FwKLt5lDasxpcSPd6zGEYyWtT5HWrZRgjO82MkvvYN0">

你这个需求很简单，看了下是string的类型数据，如果要写入到modbus寄存器，那么你只需要 通过toFloat先转成浮点数，然后再通过一下示例存储你想要的float，关于float你可能需要自己做下处理 无需修改build直接封装下吧float转成一个short范围的int16类型写入寄存器即可

![image](https://github.com/crowforkotlin/KModbus/assets/60876546/50eafefd-f0e3-464e-8e70-86353a09e0bc)

**Comment by crowforkotlin** [comment]
> 转成一个ushort

![image](https://github.com/crowforkotlin/KModbus/assets/60876546/976dae87-bbc9-4b44-85dd-bab58a2557fb)

```kotlin
@OptIn(ExperimentalStdlibApi::class)
fun main() {
    val array = ByteBuffer.wrap(ByteArray(4)).putFloat("156.7".toFloat()).array()
    println(array.map { it.toHexString() })
    println(((array[0].toInt() and 0xFF) shl 8).toShort() or (array[1].toInt() and 0xFF).toShort())
    println(((array[2].toInt() and 0xFF) shl 8).toShort() or (array[3].toInt() and 0xFF).toShort())
    println(ByteBuffer.wrap(ByteArray(2)).putShort(17180).array().map { it.toHexString() })
    println(ByteBuffer.wrap(ByteArray(2)).putShort(-19661).array().map { it.toHexString() })
    println("${toUInt16(array, 2)} = 65535 - 19661")
}

/**
 * ● 有符号Int16
 *
 * ● 2024-01-10 17:46:26 周三 下午
 * @author crowforkotlin
 */
fun toUInt16(array: ByteArray, index: Int): Int {
    return (((array[index].toInt() and 0xFF) shl 8) or (array[index + 1].toInt() and 0xFF))
}
/**
 * ● 无符号Int16
 *
 * ● 2024-01-10 17:46:17 周三 下午
 * @author crowforkotlin
 */
fun toInt16(array: ByteArray, index: Int): Int {
    return (((array[index].toInt() and 0xFF) shl 8).toShort() or (array[index + 1].toInt() and 0xFF).toShort()).toInt()
}
```

**Comment by hike2008** [comment]
<img width="432" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/f6c0bb73-c612-4b37-9896-eed61abe1fb0">

最后问个问题哈，这样的3字节的参数的协议，是 写入多个线圈寄存器 还是 写入多个保持寄存器 呢，具体值，测试命令= 1，测试参数 = 100，这种情况下应该如何将1 和 100 转换为 intArray 呢，不胜感激

**Comment by crowforkotlin** [comment]
三字节情况比较特殊 根据图片可以看出 data0 = 8bit       data1-2=16bit 这种建议你把数据进行手动转换，写多线圈不合理每个寄存器代表1bit，写多保持寄存器也不合理(因为这个是每个寄存器都表示16bit)综上所述

你需要手动转换数据 假设给出数据 100,2000那么100满足8bit无符号范围0-255，直接写100 
2000刚好在short无符号范围0-65535 可以写成两个字节

假设数据300, 70000 那么就超出了max最大值不合理 此时相当于无效值(一般不会超出 超出的话默认取最大即可)

int转字节 建议通过左移运算等...可看上面评论的代码

有问题可以直接问，有空就能解答，并不会打扰

**Comment by crowforkotlin** [comment]
但如果是按照官方modbus标准协议来定制的话 那图片上的8bit不合理 应该是写多个保持寄存器，即每一个寄存器的大小最大都为16bit

> <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/8948629/296764429-f6c0bb73-c612-4b37-9896-eed61abe1fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjU4ODksIm5iZiI6MTcwNTMyNTU4OSwicGF0aCI6Ii84OTQ4NjI5LzI5Njc2NDQyOS1mNmMwYmI3My1jNjEyLTRiMzctOTg5Ni1lZWQ2MWFiZTFmYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTMzMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTMwZjA0NDFlMzM1YTdhMDQ1ZTgyZTQ3ZjFiMDg5MDUyNDNlYjBkODY1N2M0NTc4ODFiZjc4ZTk4ZmM0ZjgwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CgO8oDChWS06nm74krpri_6pfo5tHNP1tuCojrXkBdE">
> 最后问个问题哈，这样的3字节的参数的协议，是 写入多个线圈寄存器 还是 写入多个保持寄存器 呢，具体值，测试命令= 1，测试参数 = 100，这种情况下应该如何将1 和 100 转换为 intArray 呢，不胜感激

**Comment by crowforkotlin** [comment]
> <img alt="image" width="432" src="https://private-user-images.githubusercontent.com/8948629/296764429-f6c0bb73-c612-4b37-9896-eed61abe1fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjU4ODksIm5iZiI6MTcwNTMyNTU4OSwicGF0aCI6Ii84OTQ4NjI5LzI5Njc2NDQyOS1mNmMwYmI3My1jNjEyLTRiMzctOTg5Ni1lZWQ2MWFiZTFmYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMTMzMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTMwZjA0NDFlMzM1YTdhMDQ1ZTgyZTQ3ZjFiMDg5MDUyNDNlYjBkODY1N2M0NTc4ODFiZjc4ZTk4ZmM0ZjgwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CgO8oDChWS06nm74krpri_6pfo5tHNP1tuCojrXkBdE">
> 最后问个问题哈，这样的3字节的参数的协议，是 写入多个线圈寄存器 还是 写入多个保持寄存器 呢，具体值，测试命令= 1，测试参数 = 100，这种情况下应该如何将1 和 100 转换为 intArray 呢，不胜感激

实际上这里应该是用的写多个保持寄存器 0x代表16机制，而图中只说写3字节，实属有点矛盾，那这样的话直接写对个保持寄存器就好了

**Comment by hike2008** [comment]
是否最终数据实际应该是这样？

<img width="1259" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/5214da8e-856f-492b-b3a7-ec903d857d50">

在modbus中，十六进制数据：00 0e 00 64 ，是否需要重新封装数据，将 00 0e 00 64 改成 0e 00 64  呢

看modbus的协议说明，好像都是偶数位数

<img width="776" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/d919d789-0de3-475e-9d95-a177c1375246">

**Comment by hike2008** [comment]
通讯文档中还有9个字节的，

我被通讯协议文档整懵了，空了我直接使用下位机交互试一下吧，多谢耐心解答

<img width="594" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/8948629/4913cd5d-3972-412c-9a45-1898bf931338">

**Comment by hike2008** [comment]
过来了结一下哈，我最终还是把数据发送和解析的封装做了相应的修改，因为确实协议好像跟modbus的标准文档有差异

我实际试下来，还是ByteArray更加契合我的使用场景，因此我核心的修改就是把IntArray的数据参数改成了ByteArray
