### ISSUE TITLE
databits, stopbits, and parity settings

### ISSUE THREAD

**Issue by BurakOgutken** [crowforkotlin/KModbus#2]
Hello! 
How can I configure the databits, stopbits, and parity settings?

**Comment by crowforkotlin** [comment]
I haven't extended it here yet. You need to manually modify the source code to implement it

By specific location here

https://github.com/crowforkotlin/KModbus/blob/702a9a8df9d7995b36911173ffb4f6384461d658/lib_modbus/src/main/kotlin/com/crow/modbus/serialport/SerialPortManager.kt#L102

**Comment by crowforkotlin** [comment]
You can view the latest main branch, which has updated the overload of the openSerialPort function, and supports manual configuration of the serial port check mode, stop bit, and check bit

**Comment by BurakOgutken** [comment]
Hello,
first of all, thank you very much for your answer. I can't edit and compile this application. I think you made this development, but when I add it to the implementation, the revised version doesn't come. Am I making a mistake, I wonder?

**Comment by crowforkotlin** [comment]
> 您好， 首先非常感谢您的回答。我无法编辑和编译这个应用程序。我认为您进行了此开发，但是当我将其添加到实现中时，修订版本并未出现。我想知道我是否犯了一个错误？

1: Sorry, the remote dependency aar version 1.0 has lost the so library. If you need to use it, please use the remote dependency version 1.1. It has been pushed to maven and it will take some time to update.

2: You can use the local aar file of Release 1.1 to import it into your project without introducing additional so library.
You can view the Readme introduction method

**Comment by crowforkotlin** [comment]
> 您好， 首先非常感谢您的回答。我无法编辑和编译这个应用程序。我认为您进行了此开发，但是当我将其添加到实现中时，修订版本会出现。我想知道我是否犯规有一个错误？

I tested aar locally and there was no problem

**Comment by crowforkotlin** [comment]
> 您好， 首先非常感谢您的回答。我无法编辑和编译这个应用程序。我认为您进行了此开发，但是当我将其添加到实现中时，修订版本并未出现。我想知道我是否犯了一个错误？

To run the project you need to prepare the latest Canary version of AS, or you can downgrade the Gradle version of the project to a version suitable for AS, which can be found at the following link
https://developer.android.com/build/releases/gradle-plugin

In addition to this, there are basically no references to too many third-party dependencies, and they can basically be compiled and run normally

**Comment by BurakOgutken** [comment]
Thank you, it worked flawlessly.

I'm not very familiar with Android Modbus, but I want to use a code I wrote in Node.js with the library you created. Below, I'm sharing the Node.js code and how I use it in your library. Am I using it correctly?


Node js,

```
function start() {
    client.setID(10)
    client.writeRegisters(1, [1, 0xffff])
        .then(function (data) {
            started == true;
            console.log("started 1");
        });
}
```

and this is your library is this correct ?

```
initRTU("/dev/ttyS5", 9600)
        mKModbusRtu.writeData(mKModbusRtu.buildMasterOutput(
            function = KModbusFunction.WRITE_SINGLE_REGISTER,
            slaveAddress = 10,
            startAddress = 1,
            count = 1,
            value = 1
        ))
```

**Comment by crowforkotlin** [comment]
> 谢谢，它完美地工作了。
> 
> 我对 Android Modbus 不太熟悉，但我想将我在 Node.js 中编写的代码与您创建的库一起使用。下面，我将分享 Node.js 代码以及如何在您的库中使用它。我使用正确吗？
> 
> 节点js，
> 
> ```
> function start() {
>     client.setID(10)
>     client.writeRegisters(1, [1, 0xffff])
>         .then(function (data) {
>             started == true;
>             console.log("started 1");
>         });
> }
> ```
> 
> 这是你的图书馆，这是正确的吗？
> 
> ```
> initRTU("/dev/ttyS5", 9600)
>         mKModbusRtu.writeData(mKModbusRtu.buildMasterOutput(
>             function = KModbusFunction.WRITE_SINGLE_REGISTER,
>             slaveAddress = 10,
>             startAddress = 1,
>             count = 1,
>             value = 1
>         ))
> ```

I'm not sure if 0xffff is the data from your register

If so, do you want to write a hexadecimal data 0xffff

You can set value to 0xffff, which will default to Int32 in kotlin, and it looks correct at this point

**Comment by BurakOgutken** [comment]
hi i am getting this error do you know someting ?

> type=1400 audit(0.0:2698): avc: denied { read write } for name="ttyS5" dev="tmpfs" ino=1462 scontext=u:r:system_app:s0 tcontext=u:object_r:serial_device:s0 tclass=chr_file permissive=1
> 2024-03-01 21:37:14.570 13649-13649 1.ui                    com.example.modbus                   I  type=1400 audit(0.0:2699): avc: denied { open } for path="/dev/ttyS5" dev="tmpfs" ino=1462 scontext=u:r:system_app:s0 tcontext=u:object_r:serial_device:s0 tclass=chr_file permissive=1

**Comment by crowforkotlin** [comment]
> 您好，我收到此错误，您知道吗？
> 
> > 类型= 1400审核（0.0：2698）：avc：拒绝{读写} for name =“ttyS5”dev =“tmpfs”ino = 1462 scontext = u：r：system_app：s0 tcontext = u：object_r：serial_device：s0 tclass =chr_file permissive=1 
> > 2024-03-01 21:37:14.570 13649-13649 1.ui com.example.modbus 我输入=1400 审计(0.0:2699): avc: 拒绝 { open } for path="/dev/ ttyS5" dev="tmpfs" ino=1462 scontext=u:r:system_app:s0 tcontext=u:object_r:serial_device:s0 tclass=chr_file 许可=1

Have you tried these parameters?
```
SerialPortParityFunction.NONE, stopbit = 1, databit = 8
```

I don't know why this is, maybe there are some problems in the JNI layer, you can record the entire log process from serial port opening to reading and writing data to share, or go to stackoverflow and C language third-party library modbus to see if there are such problems, It's also the first time I've met

Serial port configuration reference implementation
https://github.com/stephane/libmodbus/blob/b25629bfb508bdce7d519884c0fa9810b7d98d44/src/modbus-rtu.c#L661

**Comment by crowforkotlin** [comment]
> 您好，我收到此错误，您知道吗？
> 
> > 类型= 1400审核（0.0：2698）：avc：拒绝{读写} for name =“ttyS5”dev =“tmpfs”ino = 1462 scontext = u：r：system_app：s0 tcontext = u：object_r：serial_device：s0 tclass =chr_file permissive=1 
> > 2024-03-01 21:37:14.570 13649-13649 1.ui com.example.modbus 我输入=1400 审计(0.0:2699): avc: 拒绝 { open } for path="/dev/ ttyS5" dev="tmpfs" ino=1462 scontext=u:r:system_app:s0 tcontext=u:object_r:serial_device:s0 tclass=chr_file 许可=1
MAKE SURE THE DEVICE IS ROOTED

I feel like it's caused by no permissions.,It's not clear what this has to do with the system driver.

**Comment by BurakOgutken** [comment]
Hello again, 

I managed to send it, but now I have a problem related to reading. 


this is my nodejs code
```
  setInterval(function () {
        client.readHoldingRegisters(40090, 1).then(function (data) {
            rawMessage = createBinaryString(data.data[0]).split(/(\s+)/).filter(e => e.trim().length > 0);
            console.log(rawMessage);
        }).catch(console.log);
    }, 1000);
```

how can i read this holding register from device with your library ?

thank you

**Comment by crowforkotlin** [comment]
<img width="1067" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/60876546/5a39acf9-4696-4dd6-9cbd-cfa808d744e3">


> Hello again,
> 
> I managed to send it, but now I have a problem related to reading.
> 
> this is my nodejs code
> 
> ```
>   setInterval(function () {
>         client.readHoldingRegisters(40090, 1).then(function (data) {
>             rawMessage = createBinaryString(data.data[0]).split(/(\s+)/).filter(e => e.trim().length > 0);
>             console.log(rawMessage);
>         }).catch(console.log);
>     }, 1000);
> ```
> 
> how can i read this holding register from device with your library ?
> 
> thank you

**Comment by crowforkotlin** [comment]
> Hello again,
> 
> I managed to send it, but now I have a problem related to reading.
> 
> this is my nodejs code
> 
> ```
>   setInterval(function () {
>         client.readHoldingRegisters(40090, 1).then(function (data) {
>             rawMessage = createBinaryString(data.data[0]).split(/(\s+)/).filter(e => e.trim().length > 0);
>             console.log(rawMessage);
>         }).catch(console.log);
>     }, 1000);
> ```
> 
> how can i read this holding register from device with your library ?
> 
> thank you
The two core functions are:

1: addOnMasterReceiveListener

2: startRepeatReceiveDataTask

**Comment by BurakOgutken** [comment]
hi again 

"Rtu : ${resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG)}".info() this line giving error

Unresolved reference: info

**Comment by crowforkotlin** [comment]
@BurakOgutken 
info is a kotlin global function, you can check the source code 
<img width="709" alt="image" src="https://github.com/crowforkotlin/KModbus/assets/60876546/7bfe4af5-f60c-4728-afc5-560bb639d2c6">

**Comment by BurakOgutken** [comment]
So, which offset does this read? How does it know what to read? If I want to read from two different offsets, what should I do? Do I not have the chance to read individually like writing data?

`Rtu : KModbusRtuMasterResp(mSlaveID=10, mFunction=6, mByteCount=0, mValues=[])`

**Comment by crowforkotlin** [comment]
> 那么，这会读取哪个偏移量？它如何知道要读什么？如果我想从两个不同的偏移量读取，我该怎么办？我没有机会像写入数据一样单独读取吗？
> 
> `Rtu : KModbusRtuMasterResp(mSlaveID=10, mFunction=6, mByteCount=0, mValues=[])`

I'm sorry that this doesn't support reading alone, you can only extract the core code and modify it yourself, or I may add it later
If you want to read two offsets, you can only read the position of the last offset with the smallest value
For example
offset 1、7
Then the starting address should be 1 read 7
If you want to parse the data to the seventh holding register
Then the register data you read should be 14 bytes
At this time, if you want to get the data from the seventh register, you should be bytes 14 and 15

Here's a simple example

Two offsets 2,4
I can read from 0 to 5 registers
The byte data position from 2 should start with 2 * 2 = 4
Because it is a hold register of 16 bits
In this case, 2 bytes represent a short
The index 4 and 5, and then the two bytes can be converted to Int, if it is register data 4, then it is 4*4 = 8
Positions 8 and 9

As for why I do this, it can be read once, processed at one time, and converted at one time, and the efficiency will be much higher than that of batch reading

**Comment by crowforkotlin** [comment]
> 自己修改，或者我以后可能会添



> 13和 14



> 现在，这会读取哪个偏移量？它如何知道要读取什么？如果我想从两个不同的偏移量读取，我该怎么办？我没有像读取数据一样单独读取吗？
> 
> `Rtu : KModbusRtuMasterResp(mSlaveID=10, mFunction=6, mByteCount=0, mValues=[])`

If you specify offset and count just for one read, but for multiple reads, you can start reading directly from 0.
You can calculate the position of the data of this register yourself, so the efficiency will be much faster than batch reading, and the data will be read at one time, the maximum number of registers does not exceed 255, which is not a problem for Android, for the serial port, and the read rate of the serial port also has a great impact, and the performance of a read will be very good than multiple reads

**Comment by BurakOgutken** [comment]
for example this how can read the value from offsets

![image](https://github.com/crowforkotlin/KModbus/assets/52740998/9b6c4438-5f87-4d99-b54d-e11c562364c2)

```
private fun initRTU(ttySNumber: String, baudRate: Int) {
        mKModbusRtu.apply {
            openSerialPort(ttySNumber, baudRate, parity = SerialPortParityFunction.EVEN, dataBit = 8, stopBit = 1)

            addOnMasterReceiveListener { arrays ->
                runCatching {
                    val resp = resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG) ?: return@addOnMasterReceiveListener
                    val content = resp.mValues.toIntData(index = 1, length = 1)
                    println(content)
                }
                "Rtu : ${resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG)}".info()
            }

            startRepeatReceiveDataTask(KModbusType.MASTER);
        }
    }
```

**Comment by crowforkotlin** [comment]
> val content = resp.mValues.toIntData(index = 1, length = 1)

You're reading the register, so one register is 16 bits and two bytes
The length here should be 2
val content = resp.mValues.toIntData(index = 1, length = 2)
What this line of code means is that the read register data is converted to whole decimal, starting with index 1, and is 2 bytes (exactly 16 bits)

**Comment by BurakOgutken** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=1
                                                                                                    	at com.crow.modbus.tools.ByteExtKt.toInt16(ByteExt.kt:78)
                                                                                                    	at com.crow.modbus.tools.ByteExtKt.toIntData(ByteExt.kt:356)
                                                                                                    	at com.crow.modbus.tools.ByteExtKt.toIntData$default(ByteExt.kt:352)
                                                                                                    	at com.syssoft.myapplication.MainActivity$initRTU$1$1.invoke(MainActivity.kt:69)
                                                                                                    	at com.syssoft.myapplication.MainActivity$initRTU$1$1.invoke(MainActivity.kt:66)
                                                                                                    	at com.crow.modbus.KModbusRtu$startRepeatReceiveDataTask$1.invokeSuspend(KModbusRtu.kt:198)
                                                                                                    	at com.crow.modbus.KModbusRtu$startRepeatReceiveDataTask$1.invoke(Unknown Source:8)
                                                                                                    	at com.crow.modbus.KModbusRtu$startRepeatReceiveDataTask$1.invoke(Unknown Source:4)
                                                                                                    	at com.crow.modbus.KModbusRtu$repeatMasterActionOnRead$$inlined$onReadRepeatEnv$KModbus_1_1_release$1.invokeSuspend(SerialPortManager.kt:298)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2024-03-04 19:43:34.255  5195-5314  System.out              com.syssoft.myapplication            I  0
2024-03-04 19:43:34.256  5195-5314  kModbus                 com.syssoft.myapplication            I  Rtu : KModbusRtuMasterResp(mSlaveID=10, mFunction=6, mByteCount=0, mValues=[])
2024-03-04 19:43:34.258  5195-5314  KModbus                 com.syssoft.myapplication            I  java.lang.NegativeArraySizeException: -73
                                                                                                    	at com.crow.modbus.KModbusRtu$repeatMasterActionOnRead$$inlined$onReadRepeatEnv$KModbus_1_1_release$1.invokeSuspend(SerialPortManager.kt:288)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2024-03-04 19:43:34.546  5195-5215  System                  com.syssoft.myapplication            W  A resource failed to call close. 
2024-03-04 19:43:34.705  5195-5195  t.myapplicatio          com.syssoft.myapplication            W  Class androidx.compose.runtime.snapshots.Sn
```

**Comment by crowforkotlin** [comment]
> ```
> java.lang.ArrayIndexOutOfBoundsException: length=0; index=1
>                                                                                                     	at com.crow.modbus.tools.ByteExtKt.toInt16(ByteExt.kt:78)
>                                                                                                     	at com.crow.modbus.tools.ByteExtKt.toIntData(ByteExt.kt:356)
>                                                                                                     	at com.crow.modbus.tools.ByteExtKt.toIntData$default(ByteExt.kt:352)
>                                                                                                     	at com.syssoft.myapplication.MainActivity$initRTU$1$1.invoke(MainActivity.kt:69)
>                                                                                                     	at com.syssoft.myapplication.MainActivity$initRTU$1$1.invoke(MainActivity.kt:66)
>                                                                                                     	at com.crow.modbus.KModbusRtu$startRepeatReceiveDataTask$1.invokeSuspend(KModbusRtu.kt:198)
>                                                                                                     	at com.crow.modbus.KModbusRtu$startRepeatReceiveDataTask$1.invoke(Unknown Source:8)
>                                                                                                     	at com.crow.modbus.KModbusRtu$startRepeatReceiveDataTask$1.invoke(Unknown Source:4)
>                                                                                                     	at com.crow.modbus.KModbusRtu$repeatMasterActionOnRead$$inlined$onReadRepeatEnv$KModbus_1_1_release$1.invokeSuspend(SerialPortManager.kt:298)
>                                                                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>                                                                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>                                                                                                     	at java.lang.Thread.run(Thread.java:923)
> 2024-03-04 19:43:34.255  5195-5314  System.out              com.syssoft.myapplication            I  0
> 2024-03-04 19:43:34.256  5195-5314  kModbus                 com.syssoft.myapplication            I  Rtu : KModbusRtuMasterResp(mSlaveID=10, mFunction=6, mByteCount=0, mValues=[])
> 2024-03-04 19:43:34.258  5195-5314  KModbus                 com.syssoft.myapplication            I  java.lang.NegativeArraySizeException: -73
>                                                                                                     	at com.crow.modbus.KModbusRtu$repeatMasterActionOnRead$$inlined$onReadRepeatEnv$KModbus_1_1_release$1.invokeSuspend(SerialPortManager.kt:288)
>                                                                                                     	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>                                                                                                     	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>                                                                                                     	at java.lang.Thread.run(Thread.java:923)
> 2024-03-04 19:43:34.546  5195-5215  System                  com.syssoft.myapplication            W  A resource failed to call close. 
> 2024-03-04 19:43:34.705  5195-5195  t.myapplicatio          com.syssoft.myapplication            W  Class androidx.compose.runtime.snapshots.Sn
> ```

This has something to do with the command you send to read, and the command you read sends the parsed data bit empty and throws an exception
You have to check how you send the read data?
And what the conditions are

**Comment by BurakOgutken** [comment]
this all codes

```
initRTU("/dev/ttyS1", 9600)
        
        mKModbusRtu.writeData(mKModbusRtu.buildMasterOutput(
            function = KModbusFunction.WRITE_SINGLE_REGISTER,
            slaveAddress = 10,
            startAddress = 2,
            count = 1,
            value = 4
        ))
```

```
private fun Any?.info(tag : String = TAG, level : Int = Log.INFO)
    {
        Log.println(level, tag, this.toString())
    }

    private fun initRTU(ttySNumber: String, baudRate: Int) {
        mKModbusRtu.apply {
            openSerialPort(ttySNumber, baudRate, parity = SerialPortParityFunction.EVEN, dataBit = 8, stopBit = 1)

            addOnMasterReceiveListener { arrays ->
                runCatching {
                    val resp = resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG) ?: return@addOnMasterReceiveListener
                    val content = resp.mValues.toIntData(index = 1, length = 2)
                    println(content)
                }
                "Rtu : ${resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG)}".info()
            }

            startRepeatReceiveDataTask(KModbusType.MASTER);
        }
    }
```

**Comment by BurakOgutken** [comment]
I have an electricity meter, and I need to continuously read its data via Modbus. Actually, I want to use your library for this purpose.

**Comment by crowforkotlin** [comment]
> this all codes
> 
> ```
> initRTU("/dev/ttyS1", 9600)
>         
>         mKModbusRtu.writeData(mKModbusRtu.buildMasterOutput(
>             function = KModbusFunction.WRITE_SINGLE_REGISTER,
>             slaveAddress = 10,
>             startAddress = 2,
>             count = 1,
>             value = 4
>         ))
> ```
> 
> ```
> private fun Any?.info(tag : String = TAG, level : Int = Log.INFO)
>     {
>         Log.println(level, tag, this.toString())
>     }
> 
>     private fun initRTU(ttySNumber: String, baudRate: Int) {
>         mKModbusRtu.apply {
>             openSerialPort(ttySNumber, baudRate, parity = SerialPortParityFunction.EVEN, dataBit = 8, stopBit = 1)
> 
>             addOnMasterReceiveListener { arrays ->
>                 runCatching {
>                     val resp = resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG) ?: return@addOnMasterReceiveListener
>                     val content = resp.mValues.toIntData(index = 1, length = 2)
>                     println(content)
>                 }
>                 "Rtu : ${resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG)}".info()
>             }
> 
>             startRepeatReceiveDataTask(KModbusType.MASTER);
>         }
>     }
> ```

The written data should be read instructions instead of writing instructions, only reading will return modbus data, here I will reproduce it at work tomorrow

**Comment by BurakOgutken** [comment]
In my opinion, I should be able to read directly from the address I want, just like writedata. There should also be readdata.

**Comment by crowforkotlin** [comment]
> writeData(mKModbusRtu.buildMasterOutput(
>             function = KModbusFunction.WRITE_SINGLE_REGISTER,
>             slaveAddress = 10,
>             startAddress = 2,
>             count = 1,
>             value = 4
>         ))

I improved the code, but it can't be written and read at the same time, you need to manually write read instructions, this part is not suitable for adding to the library, it is recommended that users control it themselves

1: After writing a single hold register successfully, the slave will return and write the frame format of the instruction, there is no head and tail in this frame format, and there is no definition of how many bytes there are, which can not be read accurately, so this part cannot be implemented, of course, it is not a problem to force the implementation, this needs to be polled like a timer to check how many readable bytes there are, and then read them down for processing, this implementation will have many problems, unstable, so this implementation is not recommended

2: No matter what data you write, as long as it conforms to the standard protocol, the modbus slave will return the data to you by default, so an exception occurred when parsing and reading here, of course, this is just printing, I modified this part in the latest code, and the exception will return empty, and if it is empty, it will exit the read, because the parsing is not the correct data, if you want to parse the correct data, you should let modbus The slave returns the response data frame of the read instruction, because there is only this data frame, and the number of data bytes is given, so that the full data frame format can be read continuously

3: For complete usage, please refer to the README

```kotlin
// Only the response data of the read instruction is processed, because only the frame format of this response data meets the requirements
        addOnMasterReceiveListener { arrays -> 
              
              // No matter what data is written, as long as the parsed data is empty, it is incorrect!
              val resp: KModbusRtuMasterResp = resolveMasterResp(arrays, ModbusEndian.ARRAY_BIG_BYTE_BIG) ?: return@addOnMasterReceiveListener

              // Even if the data is parsed, it's possible that mValues will be null, and that's because the modbus slave will return a successful response by default!
              val content: Long = resp.mValues.toInt32Data(index = 0, length = 2) ?: return@runCatching
              
              "Rtu : $resp".info()
          }
```

**Comment by crowforkotlin** [comment]
use KModbus1.2.aar in github release
